### ISSUE TITLE
Bug: Toxtricity nonetype object on evolines

### ISSUE THREAD

**Issue by KyrumX** [KyrumX/python3-dutch-pokemon-fandom-scripts#16]
`Traceback (most recent call last):
  File "D:/Code/Github/python3-dutch-pokemon-fandom-scripts/test.py", line 146, in <module>
    dutch_format = scraper_class.build_template()
  File "D:\Code\Github\python3-dutch-pokemon-fandom-scripts\pokemon_dex_entries\bulbapedia\pokedex_entry_bulbapedia.py", line 50, in build_template
    return self.dex_entry.create_dutch_wiki_entry()
  File "D:\Code\Github\python3-dutch-pokemon-fandom-scripts\pokemon_dex_entries\pokedex_entry.py", line 313, in create_dutch_wiki_entry
    return self._create_dutch_wiki_entry_forms()
  File "D:\Code\Github\python3-dutch-pokemon-fandom-scripts\pokemon_dex_entries\pokedex_entry.py", line 422, in _create_dutch_wiki_entry_forms
    wiki_entry += self._create_dutch_wiki_entry()
  File "D:\Code\Github\python3-dutch-pokemon-fandom-scripts\pokemon_dex_entries\pokedex_entry.py", line 402, in _create_dutch_wiki_entry
    wiki_entry += self._build_evo_in()
  File "D:\Code\Github\python3-dutch-pokemon-fandom-scripts\pokemon_dex_entries\pokedex_entry.py", line 209, in _build_evo_in
    evo_in = current_step.next
AttributeError: 'NoneType' object has no attribute 'next'`

The Evoline of Toxtricity ends after Toxel

**Comment by KyrumX** [comment]
To elaborate, Toxtricity does not exist in the evolines, meaning it cannot be found and returns none, causing it to crash.

**Comment by KyrumX** [comment]
Fixed with #17
